### ISSUE TITLE
CORS error with Range header on Safari 14

### ISSUE THREAD

**Issue by pieterdd** [eshaz/icecast-metadata-js#207]
While solving some compatibility issues with legacy Safari versions in my own codebase, I bumped into one involving the `Range` header in the library. I tested on Safari 14 (macOS Big Sur). Here's a minimal reproduction case:

```html
<script src="https://eshaz.github.io/icecast-metadata-js/icecast-metadata-player-1.17.7.main.min.js"></script>
<script>
const player = new IcecastMetadataPlayer("https://ice4.somafm.com/groovesalad-64-aac", {
  onMetadata: (data) => {
  	document.querySelector('#metadata').innerHTML = data.StreamTitle;
  },
});
</script>
<div id="metadata">
metadata goes here
</div>
<button onclick="player.play()">
Play
</button>
```

This triggers the following errors:
![image](https://github.com/user-attachments/assets/a8bb0119-7b9a-47ff-ad82-1430c384e999)
![image](https://github.com/user-attachments/assets/c7e4a09f-a60b-4bea-8358-9c3102826495)

I'm aware that the `Range` header is [there for a reason](https://github.com/eshaz/icecast-metadata-js/issues/198). However, when I play the stream in a separate tab the stream plays fine despite the browser not sending it:

![image](https://github.com/user-attachments/assets/496972f6-21e0-4697-b4c7-ee5a9197503f)

Do you see a solution that avoids breaking other scenarios?

**Comment by eshaz** [comment]
It should retry the request without the range header when encountering the CORS error in Safari. There's some conditional logic that checks for this case, but the error details must be different in Safari 14.

Would you be able to put a breakpoint on this condition, reproduce the error in your test environment, and let me know what the value of `e.name` and `e.message` are? I can add these in as an additional check.

https://github.com/eshaz/icecast-metadata-js/blob/694b9f1b29cec1d262150a25df7393f6a7eda7ca/src/icecast-metadata-player/src/PlayerFactory.js#L143-L152

I should note, this is a bug in Safari. The `range` header is allowed per [w3c specs for fetch](https://fetch.spec.whatwg.org/#cors-safelisted-request-header) regardless of the CORS response, but Safari choose not to follow this standard for a few older versions.

**Comment by pieterdd** [comment]
Thank you for trying to accommodate Safari 14's non-compliance with the W3C spec for fetch. Here's that breakpoint in action:

![image](https://github.com/user-attachments/assets/041e6ed7-4480-4a5a-985f-33167efc5cf3)

Curiously, it appears that `e` is a promise in this context :thinking:

**Comment by pieterdd** [comment]
This looks marginally more usable:

![image](https://github.com/user-attachments/assets/dc427b4e-92f7-409f-a140-66fe2c91c516)

![image](https://github.com/user-attachments/assets/4bf0fbb3-a7d8-49eb-82e3-5bb6dd0e1b6d)

So when the promise's catch is triggered, I get these values:

- `err.name`: `TypeError`
- `err.message`: `Request header field Range is not allowed by Access-Control-Allow-Headers.`

**Comment by eshaz** [comment]
Thanks for getting that info. I've released icecast-metadata-player/1.17.8 that should fix this.

Also, thanks for all the testing and for reporting these issues as they come up. This really helps make this library better for everyone.

**Comment by pieterdd** [comment]
While validating the fix I noticed that something's still off, but I can't pinpoint what. Notice how the new condition block is not entered despite its condition evaluating to true:

![image](https://github.com/user-attachments/assets/b66fc5c0-2524-4872-aa3d-a011a105055d)

When resuming execution, I can see that the `Range` header is still present:

![image](https://github.com/user-attachments/assets/c0f8edd3-17d1-48bf-a0e6-b0cdef38416c)

**Comment by pieterdd** [comment]
Any chance it's related to the way string equality checks work in JavaScript?

I took a look at https://stackoverflow.com/questions/3586775/what-is-the-correct-way-to-check-for-string-equality-in-javascript and it appears that `"my_string".valueOf() === "other_string".valueOf()` might work. Then again, its behavior looks identical to `"my_string" === "other_string"` in the Safari 14 console:

![image](https://github.com/user-attachments/assets/a7579daa-9786-4730-bd91-3bfd3952b170)

**Comment by eshaz** [comment]
The `===` should be fine for string equality. There's probably something unexpected happening after that initial if statement on line 147 and before the return statement on 158. Could you step through this code one statement at a time and note where things don't match what the code is expecting?

https://github.com/eshaz/icecast-metadata-js/blob/90db5f316a78fb2ed3264c3c9b5873dc2887d242/src/icecast-metadata-player/src/PlayerFactory.js#L147-L158

I'm happy to continue pair programming through this github issue, but it might be faster for you to clone this repo and try things out yourself. Everything you need to do to build and run locally can be found [here](https://github.com/eshaz/icecast-metadata-js/tree/main?tab=readme-ov-file#developing-locally).

**Comment by eshaz** [comment]
Looks like I have a typo in the error message check, so that will need to be fixed... However, we might be overthinking this. Could you try out this branch?

https://github.com/eshaz/icecast-metadata-js/tree/fix-safari-14

If this change doesn't work, I'll put the promise code back into this branch and fix the typo.

**Comment by pieterdd** [comment]
I don't have a development environment on the Safari 14 machine, but I might be able to figure out some way to host the assets somewhere the machine can access them.

**Comment by pieterdd** [comment]
Hmm, looks like the debugger's watches were a red herring:

![image](https://github.com/user-attachments/assets/6f7221d2-cf9a-408a-9f4b-2e20f3840fb9)

As you can see the condition ends up being true despite `e.name` and `e.message` supposedly not matching up with the expected values.

![image](https://github.com/user-attachments/assets/5fbb6430-12c8-45b5-b255-c48d4791fc21)

Good call on your part. It's running smoothly now, and I'm glad that the working solution is simpler than the previous iteration. Thanks Ethan!

**Comment by eshaz** [comment]
Excellent, glad it worked! I've released this fix as icecast-metadata-player/1.17.9

**Comment by pieterdd** [comment]
Observed fixed in the demo player!

![image](https://github.com/user-attachments/assets/1e3f9814-e4e6-482c-a1b4-36376360374a)
